available_text_models: [
  "gpt-3.5-turbo",
  "gpt-3.5-turbo-16k",
  "gpt-4-turbo-preview",
  # "gpt-4",
  # "text-davinci-003"
  ]

info:
  gpt-3.5-turbo:
    type: chat_completion
    name: GPT 3.5 Turbo
    description: Modelo de lenguaje de OpenAI. Es <b>rápido</b> y <b>barato</b>. Ideal para tareas cotidianas. Si hay tareas que no puede manejar, pruebe el <b>GPT-4 Turbo</b>.

    price_per_1000_input_tokens: 0.0015
    price_per_1000_output_tokens: 0.002

    scores:
      Smart: 3
      Fast: 5
      Cheap: 5

  gpt-3.5-turbo-16k:
    type: chat_completion
    name: GPT 3.5-Turbo-16K
    description: GPT-3.5.Turbo-16k es un modelo ideal para tareas cotidianas y contextos mas extensos. Es <b>rápido</b> y <b>barato</b>. Ideal para tareas cotidianas. Si hay tareas que no puede manejar, pruebe el <b>GPT-4 Turbo</b>.

    price_per_1000_input_tokens: 0.003
    price_per_1000_output_tokens: 0.004

    scores:
      Smart: 3
      Fast: 5
      Cheap: 5

  gpt-4:
    type: chat_completion
    name: GPT-4
    description: GPT-4 es el modelo mas avanzado, sin embargo es mas lento y menos rentable en términos de costos como GPT-3.5 Turbo. Es la mejor opción para tareas complejas y extensas.

    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

    scores:
      Smart: 5
      Fast: 2
      Cheap: 2

  gpt-4-turbo-preview:
    type: chat_completion
    name: GPT-4 Turbo
    description: GPT-4 Turbo es una versión mas rápida y rentable de GPT-4. Es tan inteligente como GPT-4, por lo que es la mejor opción para tareas complejas y extensas.

    price_per_1000_input_tokens: 0.01
    price_per_1000_output_tokens: 0.03

    scores:
      smart: 5
      fast: 4
      cheap: 3

  text-davinci-003:
    type: completion
    name: GPT-3.5
    description: PT-3.5 es un modelo antiguo. En realidad, no hay razón para usarlo, ya que es más caro y más lento que ChatGPT, pero casi tan inteligente.

    price_per_1000_input_tokens: 0.02
    price_per_1000_output_tokens: 0.02

    scores:
      Smart: 3
      Fast: 2
      Cheap: 3

  dalle-2:
     type: image
     price_per_1_image: 0.018  # 512x512

  whisper:
    type: audio
    price_per_1_min: 0.006